#!/bin/sh
perl relations.pl -1 test1 -2 test2 -o join

perl relations.pl -1 join -p negate -c "x,k" -o neg1
perl relations.pl -1 neg1 -p project -c "y,k,x" -o proj1

perl relations.pl -1 join -p negate -c "y,k" -o neg2
perl relations.pl -1 neg2 -p project -c "k,x,y" -o proj2

perl relations.pl -1 proj1 -2 proj2 -c "y=k,k=x,x=y" -o result_or

#clean everything
rm -f join neg* proj*
